# Generated by Django 4.1.5 on 2023-01-19 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='kim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=89)),
                ('age', models.IntegerField()),
                ('addr', models.TextField()),
            ],
        ),
    ]
