# Generated by Django 4.1.5 on 2023-01-24 04:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big', '0002_kim'),
    ]

    operations = [
        migrations.CreateModel(
            name='bob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('image', models.ImageField(upload_to='')),
                ('des', models.TextField()),
            ],
        ),
    ]
