# Generated by Django 4.1.5 on 2023-01-25 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('big', '0004_alter_bob_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='one',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='img')),
                ('des', models.TextField()),
                ('date', models.DateField()),
            ],
        ),
    ]
